jenkins:
  systemMessage: "Jenkins configured as code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  jobs:
    - file: /var/jenkins_home/jobs/example-job/config.xml
