services:
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DARAVASE: testdb
      MARIADB__PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: